WeBankFinTech/DataSphereStudio

qualitis-appjoint/appjoint/src/main/java/com.webank/wedatasphere/appjoint/QualitisNodeExecution.java

Solve problem in issue：https://github.com/WeBankFinTech/DataSphereStudio/issues/10

Update QualitisNodeExecution.java to fix bug

---

bin/install.sh

Add SSH port configuration

---

docs/zh_CN/ch4/如何接入调度系统Azkaban.md

增加Azkaban的appjoint使用方法
Increase appjoint usage of Azkaban

update azkaban manual

---

docs/zh_CN/ch2/DSS快速安装使用文档.md

DSS Quick Use Document FAQ Update

---

docs/zh_CN/ch2/DSS快速安装使用文档.md

Quick installation use documentation update

---

README-ZH.md
docs/zh_CN/ch2/DSS快速安装使用文档.md
docs/zh_CN/ch3/DSS_User_Manual.md

update user manual documentation

update user manual documentation

---

docs/zh_CN/ch1/DSS安装常见问题列表.md

DSS FAQ  Update

---

conf/config.sh

Add Lite install script and documentation

---

db/dss_dml.sql

add jdbc node

---

bin/checkServices.sh

fix visualis-server status check failed after startup

---

bin/checkServices.sh
bin/install.sh
bin/start-all.sh
bin/stop-all.sh

Optimized the way to obtain the local IP address

---

bin/install.sh

Add deployment user to dss-server configuration by default

---

web/config.sh
web/install.sh
web/vue.config.js

DSS Web installation optimization

---

docs/zh_CN/ch2/DSS_LINKIS_Quick_Install.md

DSS_LINKIS Quick Install Documentation

---

docs/zh_CN/ch4/第三方系统接入DSS指南.md

close #135  modify appjoint implement doc

---

assembly/pom.xml
dss-appjoint-core/src/main/scala/com/webank/wedatasphere/dss/appjoint/execution/scheduler/ListenerEventBusNodeExecutionScheduler.scala

Update DSS with linkis version 0.9.4

Update DSS with linkis version 0.9.4

---

db/dss_ddl.sql
dss-server/src/main/java/com/webank/wedatasphere/dss/server/constant/DSSServerConstant.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dao/WorkspaceMapper.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dao/impl/workspaceMapper.xml
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dto/response/HomepageDemoInstanceVo.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dto/response/HomepageDemoMenuVo.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dto/response/HomepageVideoVo.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dto/response/OnestopMenuAppInstanceVo.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dto/response/OnestopMenuVo.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/dto/response/WorkspaceDepartmentVo.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/entity/BaseEntity.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/entity/DWSWorkspace.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/restful/WorkspaceRestfulApi.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/service/DWSWorkspaceService.java
dss-server/src/main/java/com/webank/wedatasphere/dss/server/service/impl/DWSWorkspaceServiceImpl.java

Complete part of workspace back-end develop

---

web/package.json
web/src/js/module/workbench/script/result.vue
web/src/js/module/workbench/workflow/node.vue

Fixed Python result set not showing

---

web/src/js/module/header/index.vue
web/src/js/view/newhome/module/workspace/index.vue

screen adaptation

---

db/dss_dml.sql

fix sql bug for onestop install

---

web/src/assets/styles/workspace.scss
web/src/js/view/workspace/index.vue

title style change

---

db/dss_0.9.0_update.sql

add update sql for users to update from dss-0.8.0

---

dss-server/src/main/java/com/webank/wedatasphere/dss/server/restful/UserManagerApi.java
dss-server/src/main/resources/linkis.properties
dss-server/src/main/test/com/webank/TestUnit.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/conf/DSSUserManagerConfig.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/dto/request/AuthorizationBody.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/MacroCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/AzkabanCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/KerberosCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/LdapCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/LinuxUserCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/MetastoreCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/SchedulisCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/UserAuthorizationClient.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/UserMacroCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/WorkspaceCommand.java
dss-user-manager/src/main/java/com/webank/wedatasphpere/dss/user/service/impl/YarnCommand.java
dss-user-manager/src/main/resources/read_anlexander.txt

Modify test and project name

---

dss-framework/framework-plugins/dss-framework-orchestrator-publish/src/main/java/com/webank/wedatasphere/dss/orchestrator/publish/impl/ExportDSSOrchestratorPluginImpl.java
dss-orchestrator/orchestrators/dss-workflow/dss-workflow-server/src/main/java/com/webank/wedatasphere/dss/workflow/service/impl/WorkflowNodeServiceImpl.java
dss-standard/development-standard/development-process-standard/src/main/java/com/webank/wedatasphere/dss/standard/app/development/ref/impl/CommonRequestRefImpl.java
dss-standard/dss-standard-common/src/main/java/com/webank/wedatasphere/dss/standard/common/entity/ref/AbstractRequestRef.java

Fix bug #403

---

dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/pom.xml
dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/service/impl/BuildJobActionImpl.java

Fix jobtype run error #406

---

dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/service/AzkabanProjectService.java
web/src/commonData/i18n/common/en.json
web/src/commonData/i18n/common/zh.json
web/src/js/module/project/module/projectForm.vue
web/src/js/module/workflow/module/workflowForm.vue

schedulis也做了相应修改。支持创建中文项目，项目发布，调度中项目执行、下载、上传功能。同时支持中文工作流创建及运行。

支持中文项目及工作流名称，针对dss中 的issues#279工程名与工作流名中文问题

---

dss-apps/dss-dataasset-management/pom.xml
web/src/apps/dataAssetManagement/router.js

Initialize the module info of data asset management.

Initialize the module info of data asset management.

---

dss-framework/dss-framework-orchestrator-server/src/main/java/com/webank/wedatasphere/dss/orchestrator/server/restful/OrchestratorIERestful.java
dss-standard/sso-standard/origin-sso-integration-standard/src/main/scala/com/webank/wedatasphere/dss/standard/app/sso/origin/plugin/OriginSSOMsgParseOperation.scala
sbin/dss-start-all.sh
web/src/apps/workflows/module/workflow/index.vue

修复获取SSO用户的bug
修复导入编排模式提交了多个labels的bug

fix bug #448

---

dss-appconn/appconns/dss-eventchecker-appconn/src/main/scala/com/webank/wedatasphere/dss/appconn/eventchecker/execution/EventCheckerRefExecutionOperation.scala

已经在dev1.0.1上修改
https://github.com/WeBankFinTech/DataSphereStudio/pull/434

解决schedules kill任务后EventcheckReceiver依旧在后台运行

---

web/src/common/service/api.js

location protocol from window.location

linkis href with correct location protocol 

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
.github/workflows/check_license.yml
.vscode/settings.json
README-ZH.md
README.md

Add github actions for ci and license check,  pr templates, issue templates and update readme.
- add github actions for ci and license check;
- add pr templates;
- add issue templates;
- update readme.

Add github actions for ci and license check,  pr templates, issue templates and update readme.

---

assembly/dss-package/pom.xml
dss-appconn/linkis-appconn-engineplugin/src/main/resources/linkis-engineconn.properties
dss-appconn/linkis-appconn-engineplugin/src/main/scala/org/apache/linkis/manager/engineplugin/appconn/conf/AppConnEngineConnConfiguration.scala
dss-appconn/linkis-appconn-engineplugin/src/main/scala/org/apache/linkis/manager/engineplugin/appconn/executor/AppConnEngineConnExecutor.scala
dss-apps/dss-apiservice-server/src/test/java/com/webank/wedatasphere/dss/apiservice/test/TestApiServiceDBOperation.java
pom.xml

Fix complication problems

---

dss-standard/sso-standard/sso-integration-standard/src/main/java/com/webank/wedatasphere/dss/standard/app/sso/plugin/filter/SSOPluginFilter.scala

Fix login log printing problem.

Fix login log printing problem.

---

dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/java/com/webank/wedatasphere/dss/flow/execution/entrance/restful/FlowEntranceRestfulApi.java

Remove @Override of kill method.

Remove @Override of kill method.

---

web/src/apps/apiServices/module/apiServicesExecute/index.vue
web/src/apps/scriptis/module/workbench/script/script.vue
web/src/apps/workflows/module/process/module.vue
web/src/dss/module/resourceSimple/job.vue

change api path of KIll workflow job
-  change api path of KIll workflow job
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (yes)

modify workflow api path

---

web/src/apps/workflows/view/workflow/index.vue

fix `url` define bug
- Dependencies (does it add or upgrade a dependency): ( no)
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (no)

fix: fix url define

---

dss-appconn/appconns/dss-visualis-appconn/src/main/java/com/webank/wedatasphere/dss/appconn/visualis/utils/VisualisDownloadAction.java
dss-apps/dss-apiservice-server/src/main/java/com/webank/wedatasphere/dss/apiservice/core/action/ResultSetDownloadAction.scala
dss-orchestrator/orchestrators/dss-workflow/dss-workflow-server/src/main/java/com/webank/wedatasphere/dss/workflow/entity/request/DeleteExternalNodeRequest.java
dss-orchestrator/orchestrators/dss-workflow/dss-workflow-server/src/main/java/com/webank/wedatasphere/dss/workflow/restful/NodeRestfulApi.java
pom.xml

Adapter for dss 1.0.1 to linkis 1.1.0，and fix the bug of deleting appconn node.
- Adapter to linkis1.1.0 version.
- Fix the bug of deleting appconn node.
- Dependencies (does it add or upgrade a dependency): (yes)
- Anything that affects deployment: (yes)
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (yes)
- If yes, how is the feature documented? (not documented)

Adapter for linkis-1.1.0 version.

---

conf/dss-framework-orchestrator-server.properties
conf/dss-workflow-server.properties
conf/dss.properties
dss-appconn/linkis-appconn-engineplugin/pom.xml
dss-appconn/linkis-appconn-engineplugin/src/main/resources/linkis-engineconn.properties
dss-appconn/linkis-appconn-engineplugin/src/main/resources/log4j2.xml
dss-appconn/linkis-appconn-engineplugin/src/main/scala/org/apache/linkis/manager/engineplugin/appconn/executor/AppConnComputationExecutorManagerImpl.scala
dss-apps/dss-apiservice-server/src/main/java/com/webank/wedatasphere/dss/apiservice/core/service/impl/ApiServiceImpl.java
dss-apps/dss-apiservice-server/src/main/java/com/webank/wedatasphere/dss/apiservice/core/token/JwtManager.java
dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/java/com/webank/wedatasphere/dss/flow/execution/entrance/restful/FlowEntranceRestfulApi.java
pom.xml

some bug fix.
1. Fix the problem that appconn execution engine status does not flip.
2. api service bug fix.
3. Modify execution parameter variables.
4. Fix the problem that appconn execution engine status does not flip.
5. The cookie key value is set to bdp-user-ticket-id.
6. modify wds.linkis.test.mode=false.

dss1.0.1 adopt to linkis1.1.1

---

dss-appconn/dss-appconn-manager/dss-appconn-manager-core/src/main/java/com/webank/wedatasphere/dss/appconn/manager/utils/AppInstanceConstants.java
dss-framework/dss-framework-workspace-server/src/main/java/com/webank/wedatasphere/dss/framework/workspace/restful/WorkspaceRestfulApi.java
dss-framework/dss-framework-workspace-server/src/main/java/com/webank/wedatasphere/dss/framework/workspace/service/DSSWorkspaceService.java
dss-framework/dss-framework-workspace-server/src/main/java/com/webank/wedatasphere/dss/framework/workspace/service/impl/DSSWorkspaceServiceImpl.java
dss-standard/dss-standard-common/src/main/java/com/webank/wedatasphere/dss/standard/common/desc/AppInstance.java

Fix the bug that DSS cannot jump into the external system without login.

Fix the bug that DSS cannot jump into the external system without login.

---

plugins/dolphinscheduler/dss-dolphinscheduler-client/src/main/scala/com/webank/wedatasphere/dss/plugins/dolphinscheduler/linkis/client/DSSDolphinSchedulerClient.scala

Fix the bug that DolphinScheduler do not support empty node.

Fix the bug that DolphinScheduler do not support empty node.

---

db/version_update/from_v110_to_v111.sql

Update branch 1.1.1 from master

Update branch 1.1.1 from master

---

.github/workflows/build.yml
dss-appconn/appconns/dss-sparketl-appconn/src/main/java/com/webank/wedatasphere/dss/appconn/sparketl/query/SparkEtlRefQueryJumpUrlOperation.java
dss-appconn/appconns/dss-sparketl-appconn/src/main/java/com/webank/wedatasphere/dss/appconn/sparketl/query/SparkEtlRefQueryService.java
dss-appconn/appconns/dss-sparketl-appconn/src/main/java/com/webank/wedatasphere/dss/appconn/sparketl/standard/SparkEtlDevelopmentStandard.java
dss-framework/dss-appconn-framework/src/main/java/com/webank/wedatasphere/dss/framework/appconn/restful/AppConn2LinkisRefExecutionRestfulApi.java
dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/entity/AppConn2LinkisPostAction.java
dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/execution/impl/LinkisNodeExecutionImpl.java
dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/parser/AppConn2LinkisJobParser.java
dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/parser/BML2LinkisJobParser.java
dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/parser/CodeParser.java
dss-standard/development-standard/development-process-standard/src/main/java/com/webank/wedatasphere/dss/standard/app/development/operation/AppConn2LinkisRefExecutionOperation.java
dss-standard/development-standard/development-process-standard/src/main/java/com/webank/wedatasphere/dss/standard/app/development/ref/AppConn2LinkisResponseRef.java
web/packages/workflows/module/process/component/nodeparameter.vue

Delete unuseful code and update sparketl appconn.

Delete unuseful code and update sparketl appconn.

---

dss-apps/dss-apiservice-server/src/main/java/com/webank/wedatasphere/dss/apiservice/core/constant/ApiCommonConstant.java
dss-apps/dss-apiservice-server/src/main/java/com/webank/wedatasphere/dss/apiservice/core/execute/ExecuteCodeHelper.java
dss-apps/dss-apiservice-server/src/main/java/com/webank/wedatasphere/dss/apiservice/core/restful/ApiServiceExecuteRestfulApi.java

(For example: AppConn Core defines the abstractions and interfaces of the AppConn core functions.
It is the core concept that enables DSS to easily and quickly integrate various upper-layer web systems.
Related issues: #590. )
(for example:)
- Define the core abstraction and interfaces of the AppConn;
- Define the core abstraction and interfaces of the three-level specifications of AppConn.
(or)  
This change is already covered by existing tests, such as (please describe tests).  
(or)  
This change added tests and can be verified as follows:  
(example:)  
- Added tests for creating and execute the workflow contains the nodes that DSS has integrated to go through …

fix apiService module openFile api pageSize default value bug
