assembly/src/main/assembly/assembly.xml, bin/install.sh, dss-application/src/main/java/com/webank/wedatasphere/dss/application/service/impl/ApplicationServiceImpl.java, dss-azkaban-scheduler-appjoint/pom.xml, dss-azkaban-scheduler-appjoint/src/main/assembly/distribution.xml, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/AzkabanSchedulerAppJoint.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/conf/AzkabanConf.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/hooks/LinkisAzkabanFlowPublishHook.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/hooks/LinkisAzkabanNodePublishHook.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/hooks/LinkisAzkabanProjectPublishHook.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/linkisjob/AzkabanSubFlowJobTuning.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/linkisjob/LinkisJobConverter.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/parser/AzkabanFlowParser.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/parser/AzkabanProjectParser.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/parser/LinkisAzkabanNodeParser.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/parser/LinkisAzkabanSendEmailNodeParser.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/service/AzkabanSecurityService.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/tuning/AzkabanProjectTuning.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/tuning/LinkisAzkabanFlowTuning.java, dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/tuning/LinkisShareNodeFlowTuning.java, dss-azkaban-scheduler-appjoint/src/main/resources/appjoint.properties, dss-azkaban-scheduler-appjoint/src/main/resources/log4j.properties, dss-azkaban-scheduler-appjoint/src/main/resources/log4j2.xml, dss-scheduler-appjoint-core/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/SchedulerAppJoint.java, dss-server/pom.xml, dss-server/src/main/java/com/webank/wedatasphere/dss/server/service/impl/DWSProjectServiceImpl.java
close #5 #4 
1、Modify Azkaban login error and give clear prompt
2、Change the loading mode of Azkaban to appjoint to avoid using problems when Azkaban is not installed
=> Change the loading mode of Azkaban to appjoint

bin/install.sh
1.The execution directory is separated from the installation directory.
2.The default path of visualis-server's yml file frontEnd is wrong.
3.Simple version does not install qualitis and azkaban by default.
close #13
=> One-click deployment optimization

web/package.json, web/src/js/component/editor/editor.vue
fix editor version bug ,  monaco-editor  * `getConfiguration()` is replaced by `getRawOptions()`, which returns the passed in editor options.
Issue #113 
fixed #113
=> fix editor version bug

bin/checkServices.sh, bin/install.sh, bin/start-all.sh, bin/stop-all.sh, docs/en_US/ch2/DSS Quick Installation Guide.md, docs/zh_CN/ch2/DSS快速安装使用文档.md, web/config.sh
Repair the bug that multiple ips are gotten instead of one when starting and installing.
Details see: [https://github.com/WeBankFinTech/DataSphereStudio/issues/96](url)
=> Repair the bug that multiple ips are gotten.

dss-azkaban-scheduler-appjoint/src/main/java/com/webank/wedatasphere/dss/appjoint/scheduler/azkaban/service/AzkabanProjectService.java
Use 'identity' as Content-Encoding, otherwise Jetty will reject this request.
=> 'utf-8' is not a valid value for the Content-Encoding header

dss-orchestrator/pom.xml
Define the interface of orchestration mode and basic classes, including the interface definition of orchestrator, default implementation of orchestrator, ref interface definition of orchestrator, etc.
=> Defines the basic class of the orchestration module. #354

assembly/bin/appconn-install.sh, assembly/bin/checkEnv.sh, assembly/bin/excecuteSQL.sh, assembly/bin/install.sh, assembly/config/config.sh, assembly/config/db.sh, assembly/dss-package/pom.xml, assembly/dss-package/src/main/assembly/distribution.xml, assembly/pom.xml, assembly/src/main/assembly/assembly.xml
1、Reduce package size
2、Extract public dependencies
3、Simplify user parameter configuration
=> Optimize the packaged deployment module of dss1.0.0 

dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/java/com/webank/wedatasphere/dss/flow/execution/entrance/restful/FlowEntranceRestfulApi.java, dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/scala/com/webank/wedatasphere/dss/flow/execution/entrance/job/FlowEntranceJob.scala
Fix the problem of killing workflow.
=> Fix the problem of killing workflow.

web/src/apps/workflows/module/process/index.vue
Fix dynamic node can not open
- Workflow development
=> fix: dynamic node type

web/package.json, web/src/apps/scriptis/module/workbench/container.vue, web/src/apps/workflows/service/nodeType.js, web/vue.config.js
Fix JDBC node #549 #557 #542 
This change added tests and can be verified as follows:  
Add JDBC node in workflow，then open it. 
- Dependencies (does it add or upgrade a dependency): no
- Anything that affects deployment: no
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: no
=> Fix JDBC node

pom.xml
Fix https://github.com/WeBankFinTech/DataSphereStudio/pull/583
fasterxml.jackson-databind.version
fasterxml.jackson-annotations.version
update to 2.13.3
=> Fix Jackson-annotations-2.12.6.1.jar not found

plugins/dolphinscheduler/dss-dolphinscheduler-token/src/main/java/com/webank/wedatasphere/dss/dolphinscheduler/token/restful/DolphinSchedulerTokenRestfulApi.java
https://github.com/WeBankFinTech/DataSphereStudio/issues/899
- com.webank.wedatasphere.dss.dolphinscheduler.token.restful.DolphinSchedulerTokenRestfulApi
- After integrating the dolphin scheduler component,request /dss/framework/project/ds/token api.
- See com webank. wedatasphere. dss. appconn. dolphinscheduler. operation. In the apply method of dolphin scheduler token getoperation, the expireTime field here returns the long type.
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (no)
- If yes, how is the feature documented? (not applicable)
=> fix:type conversion exception

plugins/dolphinscheduler/dss-dolphinscheduler-client/src/main/resources/linkis.properties
Let users how to modify the engine version in linkis.properties
(for example:)
- Add the engine version(Spark,Hive) in the ;DataSphereStudio/plugins/dolphinscheduler/dss-dolphinscheduler-client/src/main/resources/linkis.properties
This change added tests and can be verified as follows:  
- Modify spark version from 2.4.3 to 3.1.2
- And the sql"show databases"can run in the env (spark.version=3.1.2,linkis=1.1.1,DSS=1.1.0) 
- Anything that affects deployment: (no )
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (no)
=> Add the engine's version in the properties of ds-client 

.gitignore, conf/log4j2.xml, dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/java/com/webank/wedatasphere/dss/flow/execution/entrance/restful/FlowEntranceRestfulApi.java, dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/java/com/webank/wedatasphere/dss/flow/execution/entrance/restful/FlowExecutionRestfulApi.java, dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/scala/com/webank/wedatasphere/dss/flow/execution/entrance/conf/FlowExecutionEntranceSpringConfiguration.scala
compatibility with linkis-1.2.0 will remove the Spring bean annotation
(for example:)
- remove the linkis annotation
- fix the log4j2's logfile path.
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
=> Feat remove linkis annotations

pom.xml
There are 1 security vulnerabilities found in org.springframework:spring-core 5.2.12.RELEASE
- [CVE-2021-22060](https://www.oscs1024.com/hd/CVE-2021-22060)
Upgrade org.springframework:spring-core from 5.2.12.RELEASE to 5.2.19.RELEASE for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.springframework:spring-core to 5.2.19.RELEASE

dss-appconn/appconns/dss-dolphinscheduler-appconn/pom.xml
There are 1 security vulnerabilities found in com.google.guava:guava 28.2-android
- [CVE-2020-8908](https://www.oscs1024.com/hd/CVE-2020-8908)
Upgrade com.google.guava:guava from 28.2-android to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` succeeded locally.
Run `mvn clean test` succeeded locally. all tests passed.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade com.google.guava:guava to 30.0-jre

dss-appconn/appconns/dss-sendemail-appconn/sendemail-appconn-core/pom.xml
There are 1 security vulnerabilities found in org.apache.httpcomponents:httpclient 4.5.4
- [CVE-2020-13956](https://www.oscs1024.com/hd/CVE-2020-13956)
Upgrade org.apache.httpcomponents:httpclient from 4.5.4 to 4.5.13 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` succeeded locally.
Run `mvn clean test` succeeded locally. all tests passed.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.apache.httpcomponents:httpclient to 4.5.13

dss-appconn/appconns/dss-sendemail-appconn/sendemail-appconn-core/src/main/java/com/webank/wedatasphere/dss/appconn/sendemail/email/sender/SpringJavaEmailSender.java
修复dss工作流程节点发送邮件，邮件正文中不显示图片的问题
Spring官方说明中要求MimeMessageHelper添加文本和资源的顺序需要先确保文本再添加资源，所以做了以下两步
1.将messageHelper.setText(email.getContent(), true)放到前面
2.增加messageHelper.addAttachment(attachment.getName(), new ByteArrayDataSource(Base64.getMimeDecoder().decode(attachment.getBase64Str()), attachment.getMediaType()))用于添加资源
This change is a trivial rework / code cleanup without any test coverage.
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: (yes)
=> 修复发送邮件截图在正文中不显示的问题

db/version_update/from_v110_to_v111.sql, dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/execution/impl/LinkisNodeExecutionImpl.java, dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/job/Builder.java, dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/parser/CodeParser.java, dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/service/impl/BuildJobActionImpl.java, dss-orchestrator/orchestrators/dss-workflow/dss-linkis-node-execution/src/main/java/com/webank/wedatasphere/dss/linkis/node/execution/utils/LinkisJobExecutionUtils.java
(For example: AppConn Core defines the abstractions and interfaces of the AppConn core functions.
It is the core concept that enables DSS to easily and quickly integrate various upper-layer web systems.
Related issues: #590. )
(for example:)
- Editing failed after removing common-lang from linkis
=> Remove common-lang package adaptation after linkis1.2.0

dss-framework/dss-framework-orchestrator-server/src/main/java/com/webank/wedatasphere/dss/orchestrator/server/job/OrchestratorCopyJob.java, dss-framework/dss-framework-orchestrator-server/src/main/java/com/webank/wedatasphere/dss/orchestrator/server/service/OrchestratorService.java, dss-framework/dss-framework-orchestrator-server/src/main/java/com/webank/wedatasphere/dss/orchestrator/server/service/impl/OrchestratorFrameworkServiceImpl.java, dss-framework/dss-framework-orchestrator-server/src/main/java/com/webank/wedatasphere/dss/orchestrator/server/service/impl/OrchestratorServiceImpl.java
目前存在bug，复制flow后，发布复制的新的flow，然后报发布失败。在复制流程中增加了与下层平台交互，并持久化关联信息的逻辑
- 在OrchestratorCopyJob中的run方法中增加了逻辑
- 在OrchestratorService接口中增加了copyOrchestrator方法并在OrchestratorServiceImpl中实现了它
- 将OrchestratorFrameworkServiceImpl中的tryOrchestrationOperation从private变成public
代码经过了以上流程的测试
- Dependencies (does it add or upgrade a dependency): no
- Anything that affects deployment: no
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
=> fixbug:解决复制flow后发布到调度平台失败的问题

dss-appconn/appconns/dss-schedulis-appconn/src/main/java/com/webank/wedatasphere/dss/appconn/schedulis/utils/SchedulisHttpUtils.java
optimize  schedulis returns empty ResponseBody (ResponseBody is null ) 
This change is a trivial rework / code cleanup without any test coverage.   yes
- Dependencies (does it add or upgrade a dependency):  no
- Anything that affects deployment: no 
- The Core framework, i.e., AppConn, Orchestrator, ApiService.: no
=> Branch 1.1.1
